version: '2'
services:
  piwik:
    image: piwik
    volumes:
      - piwik-source-vol:/var/www/html
      - ./piwik.php.ini:/usr/local/etc/php/conf.d/piwik.php.ini
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    container_name: piwik-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - piwik-mariadb-vol:/var/lib/mysql
  nginx:
    image: bitnami/nginx
    container_name: piwik-nginx
    restart: always
    links:
      - piwik
    volumes:
      - ./vhost.conf:/bitnami/nginx/conf/vhosts/piwik.conf
      - piwik-source-vol:/var/www/html
    ports:
      - "3000:80"

volumes:
  piwik-mariadb-vol:
    external: true
  piwik-source-vol:
    external: true
